export const styles = {
    login_wrapper: {
        display: "flex",
        height: "100vh",
        width: "100%",
        backgroundColor: "white",
        flexDirection: { md: "row", xs: "column" },
    },
    login_container1: {
        display: "flex",
        flex: { md: 1, xs: 0 },
        minWidth: { md: "450px", xs: "0px" },
        maxWidth: { md: "1000px", xs: "100%" },
        backgroundColor: "#E5F1EB",
        alignItems: "center",
        justifyContent: "center",
        height: { md: "auto", xs: "100px" },
        zIndex: { xs: 10, md: "auto" },
    },
    login_container2: {
        display: "flex",
        flex: { md: 1, xs: 0 },
        minWidth: { md: "450px", xs: "0px" },
        width: { md: "auto", xs: "100%" },
        backgroundColor: "white",
        alignItems: "center",
        justifyContent: "center",
        height: { md: "auto" },
        zIndex: { md: "auto", xs: 1 },
    },
    login_tbs_logo: {
        height: { md: "500px", xs: "150px" },
    },
    login_input_container: {
        display: "grid",
        margin: "30px",
        gap: "20px",
        width: "100%",
        maxWidth: "450px",
        padding: { md: "0px", xs: "20px" },
    },
    login_with_button: {
        padding: "15px 20px",
        borderRadius: "15px",
        borderColor: "#D9D9D9",
        textTransform: "none",
        display: "flex",
        gap: "20px",
    },
    login_button: {
        display: "flex",
        padding: "15px 20px",
        borderRadius: "15px",
        textTransform: "none",
        backgroundColor: "#007C3D",
    },
};
