export const styles = {
    login_wrapper: {
        display: "flex",
        height: "100vh",
        width: "100%",
        backgroundColor: "white",
        flexDirection: { md: "row", xs: "column" },
    },
    login_container1: {
        display: "flex",
        flex: { md: 1, xs: 0 },
        minWidth: { md: "450px", xs: "0px" },
        maxWidth: { md: "1000px", xs: "100%" },
        backgroundColor: "#E5F1EB",
        alignItems: "center",
        justifyContent: "center",
        height: { md: "auto", xs: "100px" },
        zIndex: { xs: 10, md: "auto" },
    },
    login_container2: {
        display: "flex",
        flex: { md: 1, xs: 0 },
        minWidth: { md: "450px", xs: "0px" },
        width: { md: "auto", xs: "100%" },
        backgroundColor: "white",
        alignItems: "center",
        justifyContent: "center",
        height: { md: "auto" },
        zIndex: { md: "auto", xs: 1 },
    },
    login_tbs_logo: {
        height: { md: "500px", xs: "150px" },
    },
    login_input_container: {
        display: "grid",
        margin: "30px",
        gap: "20px",
        width: "100%",
        maxWidth: "450px",
        padding: { md: "0px", xs: "20px" },
    },
    login_with_button: {
        padding: "15px 20px",
        borderRadius: "15px",
        borderColor: "#D9D9D9",
        textTransform: "none",
        display: "flex",
        gap: "20px",
    },
    login_button: {
        display: "flex",
        padding: "15px 20px",
        borderRadius: "15px",
        textTransform: "none",
        backgroundColor: "#007C3D",
    },
    authenticated_container: {
        display: "flex",
        flexDirection: "column",
        minHeight: "100vh",
        backgroundColor: "#f3f4f6",
    },
    authenticated_appbar_top: {
        backgroundColor: "white",
        padding: { md: "10px 150px", xs: "10px 20px" },
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "20px",
        flexWrap: { xs: "wrap", md: "nowrap" },
    },
    authenticated_appbar_top_left: {
        display: { md: "flex", xs: "none" },
        alignItems: "center",
        gap: "20px",
        flexShrink: 0,
    },
    authenticated_appbar_top_right: {
        display: "flex",
        alignItems: "center",
        gap: "20px",
        width: { md: "auto", xs: "100%" },
        minWidth: "0px",
    },
    authenticated_login_button: {
        backgroundColor: "#007C3D",
        color: "white",
        textTransform: "none",
        padding: "5px",
        width: "150px",
        borderRadius: "20px",
    },
    authenticated_appbar_bottom: {
        padding: { md: "10px 150px", xs: "10px 20px" },
        backgroundColor: "#007C3D",
        justifyContent: "center",
    },
    authenticated_nav_link: {
        color: "white",
        textTransform: "none",
        fontWeight: 700,
        gap: "10px",
        fontSize: "14px",
    },
    navbar_header_title: {
        display: { md: "none", xs: "flex" },
        flex: 1,
        alignItems: "center",
        gap: "10px",
        color: "white",
    },
    small_navbar_link: {
        color: "#007C3D",
        textTransform: "none",
        fontWeight: 700,
        gap: "10px",
        fontSize: "14px",
        borderRadius: 0,
    },
    sidebar_link: {
        borderRadius: 0,
        gap: "10px",
        padding: "15px 20px",
        justifyContent: "start",
        backgroundColor: "#006330",
        color: "white",
        textTransform: "none",
        fontWeight: 700,
        fontSize: "13px",
    },
    footer_container: {
        backgroundColor: "#007C3D",
        padding: { md: "50px 150px", xs: "20px 20px" },
        color: "white",
        gap: "20px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
};
